version: '2'
services:
  merchandiseplatform-app:
    image: merchandiseplatform
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://merchandiseplatform-postgresql:5432/merchandiseplatform
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  merchandiseplatform-postgresql:
    extends:
      file: postgresql.yml
      service: merchandiseplatform-postgresql
